export const tableOption = {
  border: true,
  index: true,
  indexLabel: "序号",
  stripe: true,
  menuAlign: "center",
  align: "center",
  searchMenuSpan: 6,
  addBtn: false,
  // addBtnText: '创建模型',
  column: [
    {
      type: "input",
      label: "模型ID",
      prop: "modelId",
      hide: true,
      editDisplay: false,
      addDisplay: false,
    },
    {
      type: "input",
      label: "模型名称",
      prop: "modelName",
    },
    {
      type: "input",
      label: "模型描述",
      prop: "modelDesc",
    },
    {
      type: "input",
      //"label": "模型类型：0-用户自定义模型服务算子, 1-TorchServe, 2-TFServing",
      label: "模型类型",
      prop: "modelInferenceType",
      type: "select",
      rules: [
        {
          required: true,
          message: "请选择选择框",
        },
      ],
      dicData: [
        {
          label: "TorchServe",
          value: 1,
        },
        {
          label: "TFServing",
          value: 2,
        },
        {
          label: "用户自定义模型服务算子",
          value: 0,
        },
      ],
    },
    {
      type: "input",
      label: "模型状态", // 0-正在打包, 1-打包完成, 2-打包失败
      prop: "state",
      slot: true,
      editDisplay: false,
      addDisplay: false,
    },
    {
      type: "input",
      label: "model-link",
      prop: "model-link",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "model-name",
      prop: "model_name",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "version",
      prop: "version",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "model-file",
      prop: "model_file",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "serialized-file",
      prop: "serialized_file",
      viewDisplay: false,
      showColumn: false,
      //},	  {
      //  "type": "input",
      //  "label": "模型设置",
      //  "prop": "modelInferenceSetting"
    },
    {
      type: "input",
      label: "export-path",
      prop: "export_path",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "extra-files",
      prop: "extra_files",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "handler",
      prop: "handler",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "python-packages",
      prop: "python_packages",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "所属用户ID",
      prop: "userId",
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "模型创建时间",
      prop: "createTime",
      editDisplay: false,
      addDisplay: false,
      viewDisplay: false,
      showColumn: false,
    },
    {
      type: "input",
      label: "模型更新时间",
      prop: "updateTime",
      editDisplay: false,
      addDisplay: false,
      viewDisplay: false,
      showColumn: false,
    },
  ],
};
